export const HeadCells = [
    {
      id: 'sl_no',
      numeric: true,
      disablePadding: true,
      label: 'sl_no',
      field: 'sl_no',
      minWidth: 100,
      
    },
    {
      id: 'business_code',
      numeric: false,
      disablePadding: false,
      label: 'business_code',
      field : 'business_code',
      minWidth: 150,
    },
    {
      id: 'cust_number',
      numeric: true,
      disablePadding: false,
      label: 'cust_number',
      field : 'cust_number',
      minWidth: 150,
    },
    {
      id: 'clear_date',
      numeric: false,
      disablePadding: false,
      label: 'clear_date',
      field : 'clear_date',
      minWidth: 150,
    },
    {
      id: 'buisness_year',
      numeric: true,
      disablePadding: false,
      label: 'buisness_year',
      field : 'buisness_year',
      minWidth: 150,
    },
    {
      id: 'doc_id',
      numeric: true,
      disablePadding: false,
      label: 'doc_id',
      field : 'doc_id',
      minWidth: 150,
    },
    {
      id: 'posting_date',
      numeric: false,
      disablePadding: false,
      label: 'posting_date',
      field : 'posting_date',
      minWidth: 150,
    },
    {
      id: 'document_create_date',
      numeric: false,
      disablePadding: false,
      label: 'document_create_date',
      field : 'document_create_date',
      minWidth: 180,
    },
    {
      id: 'due_in_date',
      numeric: false,
      disablePadding: false,
      label: 'due_in_date',
      field : 'due_in_date',
      minWidth: 150,
    },
    {
      id: 'invoice_currency',
      numeric: false,
      disablePadding: false,
      label: 'invoice_currency',
      field : 'invoice_currency',
      minWidth: 150,
    },
    {
      id: 'document_type',
      numeric: false,
      disablePadding: false,
      label: 'document_type',
      field : 'document_type',
      minWidth: 150,
    },
    {
      id: 'posting_id',
      numeric: true,
      disablePadding: false,
      label: 'posting_id',
      field : 'posting_id',
      minWidth: 150,
    },
    {
      id: 'total_open_amount',
      numeric: false,
      disablePadding: false,
      label: 'total_open_amount',
      field : 'total_open_amount',
      minWidth: 190,
    },
    {
      id: 'baseline_create_date',
      numeric: false,
      disablePadding: false,
      label: 'baseline_create_date',
      field : 'baseline_create_date',
      minWidth: 190,
    },
    {
      id: 'cust_payment_terms',
      numeric: false,
      disablePadding: false,
      label: 'cust_payment_terms',
      field : 'cust_payment_terms',
      minWidth: 190,
    },
    {
      id: 'invoice_id',
      numeric: false,
      disablePadding: false,
      label: 'invoice_id',
      field : 'invoice_id',
      minWidth: 150,
    },
    {
      id : 'aging_bucket',
      numeric : false,
      disablePadding : false,
      label : 'aging_bucket',
      field : 'aging_bucket',
      minWidth : 150
    }
  ];
  
  